### ISSUE TITLE
Option to run docker script in foreground

### ISSUE THREAD

**Issue by CRTX** [polonskiy/crowdr#25]
Sometimes I have docker containers that are only supposed to run once and return a result.
Right now it's not possible since it's forced to run in a background process.

Currently I have to do a two commands.

`crowdr run`
`crowdr exec php phpunit`

Then I have to hack up a `tail -f /dev/null` inside my Dockerfile as the `ENTRYPOINT` to keep the container permanently running when it doesn't need to.

Can we have a flag to disable `-d` mode? I don't mind `-d` being the default mode as long as there's a way to disable it.

That way I could just do `crowdr run php phpunit`, get the output I need, get rid of my Dockerfile hack and run `phpunit` with just one command.

This would also save me from not having to manually enter a long `env` variable list that I need along with all the rest of the parameters that I'm currently manually sending to a `docker run`.

I would really appreciate if this feature could be added because I love crowdr!

**Comment by polonskiy** [comment]
Hi!
Why do you use crowdr for such containers in first place? Crowdr is a simple orchestrator-like tool.
Can you, please, provide your full config file?

**Comment by CRTX** [comment]
Yes. Although it helps me orchestrate single run foreground scripts.

Here's is a simple example of mine.

My crowdr config:

https://github.com/CRTX/AbstractFactory/blob/master/.crowdr/config.sh

But right now my travis-ci.org looks like this:

 ```yml
sudo: required

services:
    - docker

before_install:
    - phpenv config-rm xdebug.ini

install:
    - docker run --rm -v $(pwd):/app composer/composer install
    - sudo wget -O /usr/local/bin/crowdr https://raw.githubusercontent.com/polonskiy/crowdr/master/crowdr
    - sudo chmod +x /usr/local/bin/crowdr
    - crowdr build

script:
    - docker run -v $(pwd):/app --rm abstractfactory-php phpunit

after_success:
    - travis_retry docker run -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -v $(pwd):/app --rm abstractfactory-php coveralls -v
```

I have to use a long commands. I wish I could do:
```yml
script:
 - crowdr run php phpunit //I need to see foreground output

after_success:
 - travis_retry crowdr run php coveralls -v //need foreground output here too
```
These commands are easier to read but I can't see output. I also don't like I have to type `env` variables again. :(

I can only use crowdr for `crowdr build` right now.
